repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 77c3c6a34b2577d71083442326c60b8fd58926ec # frozen: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: d0bcdb35c6999a4a120b528f050d2b11778fd3d0 # frozen: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck

  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: 8bf32a5e81aa824af2cb56762c6fdee59f52c534 # frozen: v0.12.0
    hooks:
      - id: trivyfs-docker
        args: ["."]
      - id: trivyconfig-docker
        args: ["."]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude_types:
          - markdown

  - repo: https://github.com/executablebooks/mdformat
    rev: 08fba30538869a440b5059de90af03e3502e35fb # frozen: 0.7.17
    hooks:
      - id: mdformat

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: f295829140d25717bc79368d3f966fc1f67a824f # frozen: v0.41.0
    hooks:
      - id: markdownlint-fix-docker

  #  - repo: https://github.com/terraform-docs/terraform-docs
  #    rev: 2a6efef6469c3ebb961a3e1388639573d886bfbb # frozen: v0.18.0
  #    hooks:
  #      - id: terraform-docs-system
  #        args:
  #          [
  #            "markdown",
  #            "--output-file",
  #            "README.md",
  #            "--hide-empty",
  #            "--indent",
  #            "3",
  #            ".",
  #          ]

  - repo: https://github.com/golangci/golangci-lint
    rev: c2e095c022a97360f7fff5d49fbc11f273be929a # frozen: v1.60.3
    hooks:
      - id: golangci-lint-full
        entry: bash -c 'cd test && golangci-lint run --fix'
